### ISSUE TITLE
Unable to install the package 

### ISSUE THREAD

**Issue by ingviso** [billmalarky/react-native-queue#40]
Trying to install this package results in error.

I run the command:
sudo yarn add react-native-queue 

This results in the following:

```
yarn add v1.10.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > native-base@2.3.1" has incorrect peer dependency "react-native-vector-icons@~4.1.1".
warning " > react-native-firebase@5.0.0" has incorrect peer dependency "react@>= 16.5.0".
warning " > react-native-firebase@5.0.0" has incorrect peer dependency "react-native@>= 0.57.0".
warning " > react-native-fs@2.9.12" has incorrect peer dependency "react-native@^0.51.0".
warning " > react-native-fs@2.9.12" has incorrect peer dependency "prop-types@15.6.0".
warning " > react-native-fs@2.9.12" has unmet peer dependency "create-react-class@^15.6.2".
warning " > react-native-thumbnail@1.1.0" has incorrect peer dependency "react-native@^0.47.0".
warning " > @storybook/addon-storyshots@3.4.1" has unmet peer dependency "@storybook/addons@3.4.1".
warning " > @storybook/addon-storyshots@3.4.1" has unmet peer dependency "babel-core@^6.26.0 || ^7.0.0-0".
warning " > @storybook/react-native@3.4.1" has unmet peer dependency "babel-core@^6.26.0 || ^7.0.0-0".
warning " > @storybook/react-native@3.4.1" has unmet peer dependency "babel-runtime@>=6.0.0".
warning "@storybook/react-native > babel-loader@7.1.4" has unmet peer dependency "babel-core@6".
warning "@storybook/react-native > @storybook/ui > react-icons@2.2.7" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@storybook/react-native > @storybook/ui > react-modal@3.3.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16".
warning "@storybook/react-native > @storybook/ui > react-treebeard@2.1.0" has incorrect peer dependency "react-dom@^15.5.4 || ^16.0.0".
warning "@storybook/react-native > @storybook/ui > react-treebeard > velocity-react@1.4.0" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0".
warning " > babel-jest@22.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
warning " > enzyme@2.9.1" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x".
warning " > react-addons-test-utils@15.4.2" has incorrect peer dependency "react-dom@^15.4.2".
[4/4] 📃  Building fresh packages...
[-/9] ⡀ waiting...
[-/9] ⡀ waiting...
[8/9] ⡀ realm
[-/9] ⡀ waiting...
error /Users/ingvi/repositories/AppProject/node_modules/realm: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/ingvi/repositories/AppProject/node_modules/realm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@9.8.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/ingvi/repositories/AppProject/node_modules/realm/compiled/node-v59_darwin_x64/realm.node" (not found)
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.19.0/realm-v2.19.0-node-v59-darwin-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/2.19.0/realm-v2.19.0-node-v59-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.19.0/realm-v2.19.0-node-v59-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for realm@2.19.0 and node@9.8.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/2.19.0/realm-v2.19.0-node-v59-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.8.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.8.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ingvi/repositories/AppProject/node_modules/realm/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ingvi/.node-gyp/9.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ingvi/.node-gyp/9.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ingvi/.node-gyp/9.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ingvi/repositories/AppProject/node_modules/realm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/ingvi/.nvm/versions/node/v9.8.0/bin/node" "/Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/ingvi/repositories/AppProject/node_modules/realm/compiled/node-v59_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/ingvi/repositories/AppProject/node_modules/realm/compiled/node-v59_darwin_x64" "--napi_version=2" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v59" "--python=/usr/bin/python"
gyp ERR! cwd /Users/ingvi/repositories/AppProject/node_modules/realm
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ingvi/.nvm/versions/node/v9.8.0/bin/node /Users/ingvi/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ingvi/repositories/AppProject/node_modules/realm/compiled/node-v59_darwin_x64/realm.node --module_name=realm --module_path=/Users/ingvi/repositories/AppProject/node_modules/realm/compiled/node-v59_darwin_x64 --napi_version=2 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v59 --python=/usr/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ingvi/repositories/AppProject/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/Users/ingvi/.nvm/versions/node/v9.8.0/bin/node" "/Users/ingvi/repositories/AppProject/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ingvi/repositories/AppProject/node_modules/realm
node-pre-gyp ERR! node -v v9.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0

```

Using npm does not work either. Has anyone else experienced this. 
I have 
node: v9.8.0
react-native:  0.55.2

**Comment by Patrikejane** [comment]
is this issue sorted? Im also getting this error 

gyp ERR! node -v v11.5.0
gyp ERR! node-gyp -v v3.8.0

**Comment by nicemanis** [comment]
The same error appears with:
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2

While browsing for solutions, I read that realm (which is a dependency of this package) does not support node v11 (https://github.com/realm/realm-js/issues/2183)

Edit: tried to install it with node -v 10.15.1 and it works

**Comment by anshumanburman** [comment]
@nicemanis Great!!!!!!! it also worked for me. Thanks

**Comment by mohd-aidi** [comment]
my node is v12.13.0 but still cannot install using yarn.
