### ISSUE TITLE
Can't install with error MSB8020: The build t ools for v141 (Platform Toolset = 'v141') cannot be found

### ISSUE THREAD

**Issue by DiMoNTD** [billmalarky/react-native-queue#6]
I can't install this library. I have such error:

```
PS C:\GIT\rn-test-services\rntestservices> npm install --save react-native-queue

> realm@2.2.6 install C:\GIT\rn-test-services\rntestservices\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.2.6/realm-v2.2.6-node-v51-win32-x64.tar
.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@2.2.6 and node@7.6.0 (node-v51 ABI, unknown) (falling back to s
ource compile with node-gyp)

C:\GIT\rn-test-services\rntestservices\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nod
ejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\GIT\rn-test-services\rntestservices\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nod
ejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --modu
le=C:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64\realm.node --module_name=realm
--module_path=C:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64 --python=C:\Users\Ad
min\.windows-build-tools\python27\python.exe --msvs_version=2015 )  else (node "" configure --fallback-to-build --module
=C:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64\realm.node --module_name=realm --
module_path=C:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64 --python=C:\Users\Admi
n\.windows-build-tools\python27\python.exe --msvs_version=2015 )
Warning: Missing input files:
C:\GIT\rn-test-services\rntestservices\node_modules\realm\build\..\scripts\changelog-header.sh
C:\GIT\rn-test-services\rntestservices\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
C:\GIT\rn-test-services\rntestservices\node_modules\realm\build\..\scripts\test.sh
C:\GIT\rn-test-services\rntestservices\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
C:\GIT\rn-test-services\rntestservices\node_modules\realm\build\..\scripts\publish.sh
C:\GIT\rn-test-services\rntestservices\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
C:\GIT\rn-test-services\rntestservices\node_modules\realm\build\..\scripts\set-version.sh

C:\GIT\rn-test-services\rntestservices\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nod
ejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C
:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64\realm.node --module_name=realm --mo
dule_path=C:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64 )  else (node "" build -
-fallback-to-build --module=C:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64\realm.
node --module_name=realm --module_path=C:\GIT\rn-test-services\rntestservices\node_modules\realm\compiled\node-v51_win32
_x64 )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [C:\GIT\rn-test-services\rntestservices\node_modules\realm\bui
ld\OpenSSL.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [C:\GIT\rn-test-services\rntestservices\node_modules\realm\bui
ld\scripts.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [C:\GIT\rn-test-services\rntestservices\node_modules\realm\bui
ld\vendored-realm.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
76:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\GIT\\rn-test-services\\rntestservices\\node_modules\
\realm\\compiled\\node-v51_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\GIT\\rn-test-services\\rntest
services\\node_modules\\realm\\compiled\\node-v51_win32_x64"
gyp ERR! cwd C:\GIT\rn-test-services\rntestservices\node_modules\realm
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\GIT\rn-test-service
s\rntestservices\node_modules\realm\compiled\node-v51_win32_x64\realm.node --module_name=realm --module_path=C:\GIT\rn-t
est-services\rntestservices\node_modules\realm\compiled\node-v51_win32_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\GIT\rn-test-services\rntestservices\node_modules\node-pre-gy
p\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\GIT\\rn-test-services\\rntestservices\\node_modules
\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\GIT\rn-test-services\rntestservices\node_modules\realm
node-pre-gyp ERR! node -v v7.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\GIT\rn-test-services\rntestservices\node_modules\r
ealm\compiled\node-v51_win32_x64\realm.node --module_name=realm --module_path=C:\GIT\rn-test-services\rntestservices\nod
e_modules\realm\compiled\node-v51_win32_x64' (1)
rntestservices@0.1.0 C:\GIT\rn-test-services\rntestservices
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN react-native-maps@0.19.0 requires a peer of react@16.0.0 but none was installed.
npm WARN react-native-maps@0.19.0 requires a peer of react-native@0.51.0 but none was installed.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "--save" "react-native-queue"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! realm@2.2.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.2.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the realm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs realm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls realm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GIT\rn-test-services\rntestservices\npm-debug.log
```

I tried all methods to install MSBuildTools:
- installed library [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)
- installed separatly [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)

But error don't gone.
What I need to do, to install this library?

OS: Win 10
NodeJS: v7.6.0
NPM: 4.1.2
Python: 3.4.3
MSBuild: 14.0.25420.1

**Comment by DiMoNTD** [comment]
Closing issue.
I  have updated nodejs to version 8.9.4, and now it's ok
